"""
backend/services/advisor_memory_manager.py

In-process conversational memory for the AI Advisor.

Design:
  - Keyed by session_id (UUID stub generated by client or server)
  - Stores the last N turns and the active crop/state context
  - Supports "follow-up inheritance": if the next question omits crop/state,
    the session's last known crop/state is used automatically
  - TTL: 2 hours of inactivity (pruned lazily on next access)
  - Max turns per session: 10 (FIFO eviction)

Limitation (Phase 1B):
  Storage is per-process. Multi-worker deployments (uvicorn --workers N)
  will not share state. Phase 2 upgrade: swap backing store for Redis.
"""

from __future__ import annotations

import json
import logging
import threading
import time
import uuid
from typing import Optional

logger = logging.getLogger(__name__)

_TTL_SECONDS = 7200   # 2 hours
_MAX_TURNS   = 10     # turns kept per session
_MAX_Q_CHARS = 300    # question truncation for storage
_MAX_A_CHARS = 500    # answer truncation for storage


class AdvisorMemoryManager:
    """
    Thread-safe, in-process session memory.

    All public methods are synchronous — they run fast (in-memory only)
    and are called from async route handlers without await.
    """

    # Class-level store so a single instance shared across imports
    # holds the same sessions (one manager per Python process).
    _sessions: dict[str, dict] = {}
    _lock: threading.Lock = threading.Lock()

    # ── Session lifecycle ─────────────────────────────────────────────────────

    def get_or_create_session(self, session_id: str) -> dict:
        """
        Return the session dict (a copy, safe to read without holding the lock).
        Creates the session if it does not exist.
        """
        with self._lock:
            self._prune_expired()
            if session_id not in self._sessions:
                self._sessions[session_id] = _empty_session()
            else:
                self._sessions[session_id]["last_access"] = time.time()
            return dict(self._sessions[session_id])   # shallow copy

    def clear(self, session_id: str) -> None:
        """Explicitly clear a session (user-initiated reset)."""
        with self._lock:
            self._sessions.pop(session_id, None)

    # ── Turn management ───────────────────────────────────────────────────────

    def store_turn(
        self,
        session_id: str,
        question: str,
        answer: str,
        crop: Optional[str] = None,
        state: Optional[str] = None,
        intent: Optional[str] = None,
    ) -> None:
        """
        Append a completed Q-A turn to the session.
        Also updates the active crop/state and topic chain if provided.
        """
        with self._lock:
            if session_id not in self._sessions:
                self._sessions[session_id] = _empty_session()

            session = self._sessions[session_id]
            session["last_access"] = time.time()

            if crop:
                session["last_crop"] = crop
            if state:
                session["last_state"] = state

            session["turns"].append({
                "user":   question[:_MAX_Q_CHARS],
                "ai":     answer[:_MAX_A_CHARS],
                "ts":     time.time(),
                "intent": intent or "unknown",
                "crop":   crop,
            })
            # FIFO eviction
            if len(session["turns"]) > _MAX_TURNS:
                session["turns"] = session["turns"][-_MAX_TURNS:]

            # Phase 4A: maintain topic chain (last 5 intents with crop)
            if intent:
                chain = session.setdefault("topic_chain", [])
                chain.append({"intent": intent, "crop": crop})
                if len(chain) > 5:
                    session["topic_chain"] = chain[-5:]

            # Phase 4A: track all unique crops across turns
            if crop:
                seen = session.setdefault("crops_seen", [])
                if crop not in seen:
                    seen.append(crop)
                    if len(seen) > 10:
                        session["crops_seen"] = seen[-10:]

    def update_context(
        self,
        session_id: str,
        crop: Optional[str] = None,
        state: Optional[str] = None,
    ) -> None:
        """Update the inherited crop/state for a session without adding a turn."""
        with self._lock:
            if session_id not in self._sessions:
                return
            if crop:
                self._sessions[session_id]["last_crop"] = crop
            if state:
                self._sessions[session_id]["last_state"] = state

    # ── History retrieval ─────────────────────────────────────────────────────

    def get_history_string(self, session_id: str, max_turns: int = 3) -> str:
        """
        Return a compact, prompt-ready conversation history string (Phase 4A enhanced).

        Format includes topic intent label for each turn so Gemini understands
        what the user was asking about in prior exchanges.
        Returns "" if the session has no prior turns.
        """
        with self._lock:
            session = self._sessions.get(session_id)
            if not session or not session["turns"]:
                return ""
            recent = session["turns"][-max_turns:]

        lines: list[str] = []
        for i, turn in enumerate(recent, 1):
            intent_label = turn.get("intent", "")
            crop_label   = turn.get("crop", "")
            meta = " | ".join(filter(None, [intent_label, crop_label]))
            prefix = f"[{meta}] " if meta else ""
            lines.append(f"Q{i}: {prefix}{turn['user'][:150]}")
            lines.append(f"A{i}: {turn['ai'][:200]}")
        return "\n".join(lines)

    def get_topic_context(self, session_id: str) -> str:
        """
        Return a concise topic-chain summary for prompt injection (Phase 4A).

        Describes what the user has been exploring across the session
        so Gemini can reference earlier topics in its response.
        """
        with self._lock:
            session = self._sessions.get(session_id)
            if not session:
                return ""
            chain      = session.get("topic_chain", [])
            crops_seen = session.get("crops_seen", [])

        if not chain:
            return ""

        unique_intents = list(dict.fromkeys(t["intent"] for t in chain if t.get("intent")))
        crops_str = ", ".join(crops_seen[:4]) if crops_seen else ""
        topics_str = " → ".join(unique_intents[-4:])

        parts = [f"User has been asking about: {topics_str}"]
        if crops_str:
            parts.append(f"Crops discussed in this session: {crops_str}")
        return ". ".join(parts) + "."

    # ── Utilities ─────────────────────────────────────────────────────────────

    @staticmethod
    def generate_session_id() -> str:
        """Generate a new, unique session ID."""
        return f"adv_{uuid.uuid4().hex[:12]}"

    def session_exists(self, session_id: str) -> bool:
        with self._lock:
            return session_id in self._sessions

    def active_session_count(self) -> int:
        with self._lock:
            return len(self._sessions)

    def _prune_expired(self) -> None:
        """Remove sessions inactive for longer than _TTL_SECONDS. Caller holds lock."""
        now = time.time()
        expired = [
            sid for sid, s in self._sessions.items()
            if now - s["last_access"] > _TTL_SECONDS
        ]
        for sid in expired:
            del self._sessions[sid]


def _empty_session() -> dict:
    now = time.time()
    return {
        "created_at":    now,
        "last_access":   now,
        "last_crop":     None,
        "last_state":    None,
        "turns":         [],
        "topic_chain":   [],   # Phase 4A: list of {intent, crop} dicts (last 5)
        "crops_seen":    [],   # Phase 4A: all unique crops mentioned across turns
    }


# ── Optional Redis backend ─────────────────────────────────────────────────────

class RedisMemoryManager:
    """
    Redis-backed session memory — same public interface as AdvisorMemoryManager.

    Activated when ADVISOR_MEMORY_BACKEND=redis in backend/.env.
    Falls back to AdvisorMemoryManager if the redis package is absent or the
    connection fails (see _create_memory_manager()).

    Each session is stored as a JSON string under the key:
        agroprice:advisor_session:<session_id>
    with a sliding TTL equal to _TTL_SECONDS.

    Limitation: read-modify-write operations are not atomic. Under very high
    concurrency a turn may be lost. Acceptable for academic / single-server use.
    """

    _KEY_PREFIX = "agroprice:advisor_session:"

    def __init__(self, redis_client: object) -> None:
        self._client = redis_client

    # ── helpers ───────────────────────────────────────────────────────────────

    def _key(self, session_id: str) -> str:
        return f"{self._KEY_PREFIX}{session_id}"

    def _get(self, session_id: str) -> Optional[dict]:
        raw = self._client.get(self._key(session_id))
        return json.loads(raw) if raw else None

    def _set(self, session_id: str, session: dict) -> None:
        session["last_access"] = time.time()
        self._client.setex(self._key(session_id), _TTL_SECONDS, json.dumps(session))

    # ── public interface ──────────────────────────────────────────────────────

    def get_or_create_session(self, session_id: str) -> dict:
        session = self._get(session_id) or _empty_session()
        self._set(session_id, session)
        return dict(session)

    def clear(self, session_id: str) -> None:
        self._client.delete(self._key(session_id))

    def store_turn(
        self,
        session_id: str,
        question: str,
        answer: str,
        crop: Optional[str] = None,
        state: Optional[str] = None,
        intent: Optional[str] = None,
    ) -> None:
        session = self._get(session_id) or _empty_session()
        if crop:
            session["last_crop"] = crop
        if state:
            session["last_state"] = state
        session["turns"].append({
            "user":   question[:_MAX_Q_CHARS],
            "ai":     answer[:_MAX_A_CHARS],
            "ts":     time.time(),
            "intent": intent or "unknown",
            "crop":   crop,
        })
        if len(session["turns"]) > _MAX_TURNS:
            session["turns"] = session["turns"][-_MAX_TURNS:]
        if intent:
            chain = session.setdefault("topic_chain", [])
            chain.append({"intent": intent, "crop": crop})
            session["topic_chain"] = chain[-5:]
        if crop:
            seen = session.setdefault("crops_seen", [])
            if crop not in seen:
                seen.append(crop)
            session["crops_seen"] = seen[-10:]
        self._set(session_id, session)

    def update_context(
        self,
        session_id: str,
        crop: Optional[str] = None,
        state: Optional[str] = None,
    ) -> None:
        session = self._get(session_id)
        if not session:
            return
        if crop:
            session["last_crop"] = crop
        if state:
            session["last_state"] = state
        self._set(session_id, session)

    def get_history_string(self, session_id: str, max_turns: int = 3) -> str:
        session = self._get(session_id)
        if not session or not session["turns"]:
            return ""
        recent = session["turns"][-max_turns:]
        lines: list[str] = []
        for i, turn in enumerate(recent, 1):
            intent_label = turn.get("intent", "")
            crop_label   = turn.get("crop", "")
            meta = " | ".join(filter(None, [intent_label, crop_label]))
            prefix = f"[{meta}] " if meta else ""
            lines.append(f"Q{i}: {prefix}{turn['user'][:150]}")
            lines.append(f"A{i}: {turn['ai'][:200]}")
        return "\n".join(lines)

    def get_topic_context(self, session_id: str) -> str:
        session = self._get(session_id)
        if not session:
            return ""
        chain      = session.get("topic_chain", [])
        crops_seen = session.get("crops_seen", [])
        if not chain:
            return ""
        unique_intents = list(dict.fromkeys(t["intent"] for t in chain if t.get("intent")))
        crops_str  = ", ".join(crops_seen[:4]) if crops_seen else ""
        topics_str = " → ".join(unique_intents[-4:])
        parts = [f"User has been asking about: {topics_str}"]
        if crops_str:
            parts.append(f"Crops discussed in this session: {crops_str}")
        return ". ".join(parts) + "."

    @staticmethod
    def generate_session_id() -> str:
        return f"adv_{uuid.uuid4().hex[:12]}"

    def session_exists(self, session_id: str) -> bool:
        return bool(self._client.exists(self._key(session_id)))

    def active_session_count(self) -> int:
        return len(self._client.keys(f"{self._KEY_PREFIX}*"))


# ── Factory — selects backend from config ─────────────────────────────────────

def _create_memory_manager() -> "AdvisorMemoryManager | RedisMemoryManager":
    """
    Return a RedisMemoryManager if ADVISOR_MEMORY_BACKEND=redis AND the redis
    package is installed AND the server is reachable. Otherwise fall back to the
    thread-safe in-process AdvisorMemoryManager.
    """
    from backend.core.config import settings  # lazy import avoids circular dependency

    if settings.ADVISOR_MEMORY_BACKEND != "redis":
        return AdvisorMemoryManager()

    try:
        import redis as redis_lib  # type: ignore[import]
        client = redis_lib.Redis.from_url(settings.REDIS_URL, decode_responses=True,
                                          socket_connect_timeout=2)
        client.ping()
        logger.info("advisor_memory: Redis backend connected at %s", settings.REDIS_URL)
        return RedisMemoryManager(client)
    except ImportError:
        logger.warning("advisor_memory: redis package not installed — falling back to in-process store")
    except Exception as exc:
        logger.warning("advisor_memory: Redis unavailable (%s) — falling back to in-process store", exc)

    return AdvisorMemoryManager()


# Replace the simple singleton with a factory-constructed instance.
memory_manager = _create_memory_manager()
