import api from './api'

/**
 * GenAI Forecast Intelligence service (Phase 2).
 * All endpoints return deterministic, data-driven output generated by the
 * backend narrator — same contract a future streaming LLM provider will use.
 */
export const aiService = {
  /** Full insight bundle: narrative, confidence, strategy, story, anomalies. */
  async getInsights({ crop, state, days = 30 } = {}) {
    const res = await api.get('/api/ai/insights', { params: { crop, state, days } })
    return res.data
  },

  /** Context-aware copilot chat with conversation memory. */
  async chat({ message, crop, state, days = 30, history = [] } = {}) {
    const res = await api.post('/api/ai/chat', { message, crop, state, days, history })
    return res.data
  },

  /** What-if market scenario simulation. */
  async simulate({ crop, state, scenario, days = 30 } = {}) {
    const res = await api.post('/api/ai/simulate', { crop, state, scenario, days })
    return res.data
  },

  /** Scenario catalogue for the simulator UI. */
  async getScenarios() {
    const res = await api.get('/api/ai/scenarios')
    return res.data
  },

  /** Multi-crop AI comparison. */
  async compare(crops) {
    const res = await api.get('/api/ai/compare', {
      params: { crops },
      paramsSerializer: { indexes: null },   // crops=a&crops=b
    })
    return res.data
  },
}
