"""
GenAI Forecast Intelligence routes (Phase 2).

  GET  /api/ai/insights   — narrative + confidence + strategy + story + anomalies
  POST /api/ai/chat       — conversational copilot (provider-abstracted)
  POST /api/ai/simulate   — what-if market scenario simulation
  GET  /api/ai/compare    — multi-crop AI comparison
  GET  /api/ai/scenarios  — available scenario definitions

All outputs are generated by backend/services/ai_forecast_narrator.py from
real computed metrics — deterministic, cacheable, and LLM-grounding-ready.
"""
from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel, Field

from fastapi.responses import PlainTextResponse

from backend.cache.query_cache import cache_get, cache_set
from backend.core.logger import get_logger
from backend.services import ai_forecast_narrator as narrator
from backend.services import executive_intelligence as executive
from backend.services.forecast_ai_chat import chat as ai_chat, suggested_prompts
from backend.utils.validators import validate_crop, validate_state

logger = get_logger(__name__)
router = APIRouter()


def _peers() -> list[dict]:
    """Cross-crop records for comparisons (warm cache or empty)."""
    cc = cache_get("cross_crop_analytics_v3")
    return cc.get("crops", []) if cc else []


def _context_cached(crop: str, state: str, days: int) -> dict:
    key = f"ai_ctx_{crop}_{state}_{days}"
    ctx = cache_get(key)
    if ctx is None:
        ctx = narrator.build_insight_context(crop, state, days)
        cache_set(key, ctx)
    return ctx


@router.get("/insights")
def get_ai_insights(
    crop: str = Query(...),
    state: str = Query(...),
    days: int = Query(default=30, ge=7, le=365),
) -> dict:
    """Full AI insight bundle for the selected crop/state/horizon."""
    try:
        crop, state = validate_crop(crop), validate_state(state)
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc))

    key = f"ai_insights_{crop}_{state}_{days}"
    cached = cache_get(key)
    if cached is not None:
        return cached

    ctx = _context_cached(crop, state, days)
    peers = _peers()

    has_data = ctx.get("has_data", False)
    tier = ctx.get("tier", {}) if has_data else {}
    pair_tier = tier.get("tier") if has_data else "D"
    # Phase 2.5 intelligence mode for THIS crop+state pair (not the home state)
    mode = {"A": "full", "B": "moderate", "C": "sparse"}.get(pair_tier, "analytics")

    result = {
        "crop": crop, "state": state, "days": days,
        "has_data": has_data,
        "mode": mode,
        "context_summary": {
            "tier":             pair_tier if has_data else None,
            "cv":               ctx.get("volatility", {}).get("cv") if has_data else None,
            "momentum":         ctx.get("momentum", {}).get("score") if has_data else None,
            "phase":            (ctx.get("seasonal") or {}).get("current_phase") if has_data else None,
            # full per-pair diagnostics — the page header must use THESE,
            # never the crop's home-state coverage record
            "training_days":    tier.get("training_days"),
            "recent_days_365":  tier.get("recent_days_365"),
            "continuity_score": tier.get("continuity_score"),
            "anomaly_count":    len(ctx.get("anomalies", [])) if has_data else None,
            "reliability":      ctx.get("quality", {}).get("reliability") if has_data else None,
            "reliability_score": ctx.get("quality", {}).get("score") if has_data else None,
            "avg_30d":          ctx.get("avg_30d") if has_data else None,
        },
    }

    # Phase 3: explainability + smart insight cards (both modes, data-derived)
    result["insight_cards"] = narrator.build_insight_cards(ctx)
    result["drivers"] = narrator.build_drivers(ctx)

    if mode == "analytics":
        # Mode D: regional intelligence INSTEAD of forecast copilot content
        availability = narrator.state_availability(crop)
        result["regional"] = narrator.build_regional_intelligence(
            crop, state, ctx, availability
        )
        result["suggested_prompts"] = [
            f"Which states have good {crop} data?",
            f"Compare {crop} markets across states",
            "What does analytics-only mode mean?",
        ]
    else:
        result.update({
            "narrative": narrator.build_narrative(ctx),
            "confidence": narrator.build_confidence(ctx),
            "strategy": narrator.build_strategy(ctx),
            "trend_story": narrator.build_trend_story(ctx, peers),
            "anomaly_explanations": narrator.explain_anomalies(ctx),
            "suggested_prompts": suggested_prompts(ctx),
        })

    cache_set(key, result)
    return result


class ChatTurn(BaseModel):
    role: str           # 'user' | 'ai'
    text: str


class ChatRequest(BaseModel):
    message: str = Field(..., min_length=1, max_length=500)
    crop: str
    state: str
    days: int = Field(default=30, ge=7, le=365)
    # Phase 2.5: conversation memory — the client sends recent turns so the
    # engine can resolve follow-ups ("in 2024"), inherited crops, and topics.
    history: list[ChatTurn] = Field(default_factory=list, max_length=12)


@router.post("/chat")
def post_ai_chat(req: ChatRequest) -> dict:
    """Stateful, intent-aware forecast chat (rule-based provider in Phase 2.5)."""
    try:
        crop, state = validate_crop(req.crop), validate_state(req.state)
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc))

    history = [{"role": t.role, "text": t.text} for t in req.history]
    try:
        result = ai_chat(req.message, crop, state, req.days, _peers(), history)
    except Exception as exc:
        logger.error("ai_chat_error", crop=crop, state=state, error=str(exc))
        raise HTTPException(
            status_code=500,
            detail={"category": "pipeline_error",
                    "message": "The analytics engine encountered an error — please retry."},
        )
    logger.info("ai_chat", crop=crop, state=state, intent=result.get("intent"))
    return result


class SimulateRequest(BaseModel):
    crop: str
    state: str
    scenario: str
    days: int = Field(default=30, ge=7, le=365)


@router.post("/simulate")
def post_ai_simulate(req: SimulateRequest) -> dict:
    """What-if market scenario simulation from real crop characteristics."""
    try:
        crop, state = validate_crop(req.crop), validate_state(req.state)
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc))

    ctx = _context_cached(crop, state, req.days)
    try:
        return narrator.simulate_scenario(ctx, req.scenario)
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc))


@router.get("/scenarios")
def get_scenarios() -> dict:
    """Scenario catalogue for the simulator UI."""
    return {
        "scenarios": [
            {"key": k, "label": v["label"], "icon": v["icon"], "description": v["desc"]}
            for k, v in narrator.SCENARIOS.items()
        ]
    }


# ── Phase 4: executive intelligence ──────────────────────────────────────────

@router.get("/executive")
def get_executive_summary() -> dict:
    """Market command center: KPIs, pulse cards, insight ribbon, ranked alerts."""
    key = "executive_summary_v1"
    cached = cache_get(key)
    if cached is not None:
        return cached
    result = executive.executive_summary(_peers())
    if result.get("ready"):
        cache_set(key, result)
    return result


@router.get("/pair-matrix")
def get_pair_matrix() -> dict:
    """crop×state metric grid for heatmaps (cached; one SQL pass)."""
    key = "pair_matrix_v1"
    cached = cache_get(key)
    if cached is not None:
        return cached
    result = executive.pair_matrix()
    cache_set(key, result)
    return result


@router.get("/battle")
def get_battle(
    a: str = Query(..., description="First crop"),
    b: str = Query(..., description="Second crop"),
) -> dict:
    """AI battle-card comparison across 6 scored dimensions."""
    try:
        a, b = validate_crop(a), validate_crop(b)
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc))
    result = executive.battle(_peers(), a, b)
    if "error" in result:
        raise HTTPException(status_code=422, detail=result["error"])
    return result


class StrategyRequest(BaseModel):
    risk_appetite: str = Field(default="medium", pattern="^(low|medium|high)$")
    horizon: str = Field(default="medium", pattern="^(short|medium|long)$")
    storage: str = Field(default="limited", pattern="^(none|limited|good)$")
    state: str | None = None


@router.post("/strategy")
def post_strategy(req: StrategyRequest) -> dict:
    """Decision-intelligence recommendations from user constraints."""
    state = None
    if req.state:
        try:
            state = validate_state(req.state)
        except ValueError as exc:
            raise HTTPException(status_code=422, detail=str(exc))
    return executive.strategy(_peers(), {
        "risk_appetite": req.risk_appetite, "horizon": req.horizon,
        "storage": req.storage, "state": state,
    })


@router.get("/timeline")
def get_timeline(crop: str = Query(...), state: str = Query(...)) -> dict:
    """Market history storytelling events with AI annotations."""
    try:
        crop, state = validate_crop(crop), validate_state(state)
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc))
    key = f"timeline_{crop}_{state}"
    cached = cache_get(key)
    if cached is not None:
        return cached
    result = executive.timeline(crop, state)
    cache_set(key, result)
    return result


@router.get("/report", response_class=PlainTextResponse)
def get_report(
    crop: str = Query(...),
    state: str = Query(...),
    days: int = Query(default=30, ge=7, le=365),
) -> str:
    """Downloadable markdown crop outlook report (deterministic)."""
    try:
        crop, state = validate_crop(crop), validate_state(state)
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc))
    return executive.outlook_report(crop, state, days)


@router.get("/compare")
def get_ai_compare(
    crops: list[str] = Query(..., min_length=2, max_length=6),
) -> dict:
    """Multi-crop AI comparison from the cross-crop analytics cache."""
    try:
        wanted = [validate_crop(c) for c in crops]
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc))

    peers = _peers()
    if not peers:
        raise HTTPException(
            status_code=503,
            detail="Cross-crop analytics cache is still warming — retry shortly.",
        )
    records = [p for p in peers if p["crop"] in wanted]
    return narrator.compare_crops(records)
